### ISSUE TITLE
Question about algorithm

### ISSUE THREAD

**Issue by johnrachwan123** [mkazhdan/PoissonRecon#106]
Hello, I have reached a limit of depth 13 while enabling the BIG_DATA variable, I would like to know if you think if its possible to implement out-of-core on the current algorithm because I am very interested in doing it.

**Comment by mkazhdan** [comment]
Unfortunately, I think it would be non-trivial. The hardest part, I think, would be the construction of the octree. After that, things are essentially implemented in a streaming fashion (for memory efficiency) so making that work for streaming from disk should not be too too bad. 

However, given the efforts that went into putting together the original out-of-core implementation, I would expect it would take significant efforts.

**Comment by johnrachwan123** [comment]
Okay, I understand. I also came across a GPU version of your algorithm published by Microsoft researchers but they haven't made their code publicly available. Since the pc I'm using has four Nvidia V20s I am contemplating implementing it.
Do you think it is worth the effort? ( I mean given really good GPUs do you think it is a good alternative to the CPU version)

**Comment by mkazhdan** [comment]
You're referring to the "Highly parallel..." paper? I'm not that familiar with it. However, that will only improve running time. It won't solve the memory problem.

**Comment by johnrachwan123** [comment]
Alright, Thank you for your help!

**Comment by johnrachwan123** [comment]
I would like to understand the theory behind ChunkPly, is there a published paper or something i could consult?

**Comment by mkazhdan** [comment]
Nope.

It's Jaime simple code for breaking up geometry looking at which cell of a regular grid it falls into. (Useful to allow visualizations of reconstructions that are too big to be viewed as a whole.) For points, the cell is determined by the point's position. For triangles it's determined by the center of mass. 

There is also a parameter that allows for padding out so that a point/triangle falls into a cell if it's close by but not actually aside. (For applications where context is useful.)
