### ISSUE TITLE
Lucy.ply  [ERROR] Failed to find property in ply file: nx

### ISSUE THREAD

**Issue by knihtyang** [mkazhdan/PoissonRecon#13]
Hi.
I'm trying to run the last version on a Windows 7 system. I have installed the VS2013 package. while running   the Lucy model ,there is wrong that   Failed to find property in ply file: nx. but eagle.points.ply's 
property containing nx,ny,nz  is ＯＫ

**Comment by mkazhdan** [comment]
Can you share the ply file for the Lucy model?

 

Thanks,

Misha

**Comment by knihtyang** [comment]
I send it to your mailbox,thanks.

**Comment by mkazhdan** [comment]
I haven't received it. Can you try resending?

**Comment by knihtyang** [comment]
Are you  received it?

**Comment by mkazhdan** [comment]
Nope. Nothing. What address did you use?

**Comment by knihtyang** [comment]
I sent to PoissonRecon@noreply.github.com, oh,I got it from http://graphics.stanford.edu/data/3Dscanrep/lucy.tar.gz. May I have your contact information? I promise to protect your privacy.

**Comment by knihtyang** [comment]
I sent to PoissonRecon@noreply.github.com, oh,I got it from http://graphics.stanford.edu/data/3Dscanrep/lucy.tar.gz. May I have your contact information? I promise to protect your privacy.mine is 1036791720@qq.com

**Comment by mkazhdan** [comment]
I downloaded the file from the Stanford repository. However, when I run "more lucy.ply" I get:
   ply
   format binary_big_endian 1.0
   element vertex 14027872
   property float x
   property float y
   property float z
   element face 28055742
   property list uchar int vertex_indices
   end_header
This implies that the vertices in the .ply file have positions but do not have normals.
As a result, the file does not have sufficient data (e.g. normals) for reconstruction.

-- Misha

**Comment by knihtyang** [comment]
can you help me how get the sufficient data (eg.normal) as eagle.points.ply?

**Comment by mkazhdan** [comment]
Depending on the type of data you have, there are three standard ways of doing this:

1.       If your input is a “bag of points” you can estimate the normal _lines_ at each sample by finding the k nearest neighbors (e.g. using the ANN package) and then finding the normal of the plane that best fits the k+1 points.
However, you still have choose a sign for the normal. One way to do this is to follow the approach of Hoppe et al. in “Surface reconstruction from unorganized points”, which builds a k nearest neighbor graph, computes a minimal spanning tree, and propagates normal orientation by traversing the tree.

2.       If your input is a set of range scans with camera parameters, then typically each scan has the topology of a (partial) grid, so neighbors are explicitly defined and you can use these to estimate the normal lines. Then, you choose the sign of the normal that makes the dot-product between the normal and the camera’s view direction negative. (Otherwise the point would not be visible to the camera.)

3.       If your input is an oriented triangle mesh (like the Lucy model you pointed me to) then you can just set the normal at a vertex to the (normalized) area-weighted sum of the normals of the adjacent triangles. However, this does beg the question: “If you already have a triangle mesh, why are you running reconstruction on the vertices?” (If the reason is to generate a coarser mesh, you may want to consider applications like MeshLab that implement a number of different algorithms for triangle mesh decimation.)

 

-- Misha

**Comment by knihtyang** [comment]
thanks for your explanation,I try it

**Comment by knihtyang** [comment]
Misha,I'm having problems again . when eagle.points.ply‘s some parameters  pointWeight=0 and depth=10,the resulting  time（Wall/User/kernel）:2556.53/2528.36/2.87,if CUP time =2531.23 seconds  right,  CPU run time is too surprising

**Comment by mkazhdan** [comment]
I am afraid I do not understand the issue…

However, when running the eagle model on my machine (with parameters “--in eagle.ply --pointWeight 0 --depth 10 --verbose --performance --out foo.ply”) my running times are about 50 times faster:

Time (Wall/User/Kernel): 41.55 / 38.33 / 2.53

Peak Memory (MB): 829

 

-- Misha

**Comment by knihtyang** [comment]
I don't know why running the lastest version 9.0 on a Windows 7, 64-bit system VS2015 package( with these paramers  "Bin\x64\Debug\PoissonRecon.exe --in data\PointWeight\eagle.points.ply  --pointWeight 0  --depth 10 --verbose  --performance --out data\PointWeight\eagle.unscreend0d.ply 
 ") my results :
**Input points /Samples:796825/694072**
......
**# Time (Wall/User/Kernel):646.95/552.49/50.34
Peak Memory (MB):843**
![image](https://cloud.githubusercontent.com/assets/13538712/19237142/cca02ece-8f2d-11e6-8f7d-9afe5baa4121.png)
 this eagle.ply model's  size is 21.2MB ,right?

**Comment by mkazhdan** [comment]
I would try one of two things:

1.       Compile under “release” mode and run that.

2.       In Visual Studios, go to the project properties and make sure that in “C/C++” -> “Language” the Open MP support is enabled. (I know that it is in the release version. I’m not sure that it is in debug.) It could be case that you’re compilation is single-threaded, which would explain the slower running times.

**Comment by knihtyang** [comment]
The program is still running, according to  method II, but the operating time changes little or even slightly larger, and I try the method one
![image](https://cloud.githubusercontent.com/assets/13538712/19239596/5c768524-8f39-11e6-9ff3-957b1524088a.png)

**Comment by knihtyang** [comment]
when I running  compile under “release” mode,this time  
 **Time (Wall/User/Kernel):43.89/41.59/1.67
Peak Memory (MB):713**
Why did this result

**Comment by mkazhdan** [comment]
I am seeing similar performance when running in Debug mode.

Things are a little better when I enable the enhanced instruction set “Advanced Vector Extensions 2 (/arch:AVX2)”, but still substantially slower than running in release mode.

**Comment by knihtyang** [comment]
when I running compile under “release” mode（with some paramers "Bin\x64\Release\PoissonRecon.exe --in data\eagle.points.ply  --pointWeight 4  **--color 16** --depth 8 --out data\eagle\eagle.screend8d.ply **--density --voxel eagel.screend10.iso --voxelDepth 8 --performance  --bType 2**"）,it don't run. What is the function of   color <pull factor>

**Comment by mkazhdan** [comment]
I’m not sure I understand your question: What do you mean by “it don’t run”?

The “--color” parameter specifies that the input points come equipped with color. (The actual value of the parameter is something controls how quickly color information gets diffused into regions where there are no samples, which mostly affects how color is extrapolated when there are holes in the input that are closed in the reconstruction.)

 

-- Misha

**Comment by knihtyang** [comment]
when running  the  test.bat file （with some paramers "Bin\x64\Release\PoissonRecon.exe --in data\eagle.points.ply --pointWeight 4 **--color 16** --depth 8 --out data\eagle\eagle.screend8d.ply -**-density --voxel eagel.screend10.iso --voxelDepth 8 --performance --bType 2**"）,After tens of seconds it prompts PoissonRecon.exe to stop running

**Comment by mkazhdan** [comment]
That’s very strange indeed.

 

When I run the executable from http://www.cs.jhu.edu/~misha/Code/PoissonRecon, things seem to work (output at the bottom).

Does the prompt give any information about why the executable failed?

Did you compile the code yourself are you using the executable provided with the website?

How old is the machine you’re running on? (I ask because there has been a problem that older PCs don’t support the “Advanced Vector Extensions 2 (/arch:AVX2)” flag under Properties -> C/C++ -> Enable Enhanced Instruction Set.)

 

-- Misha

 

 

C:\ >PoissonRecon.exe --in eagle.points.ply --pointWeight 4 --color 16 --depth 8 --out eagle.out.ply --density --voxel eagle.out.iso --voxelDepth 8 --performance --bType 2 --verbose

Running Screened Poisson Reconstruction (Version 9.0)

        --bType 2

        --in eagle.points.ply

        --depth 8

        --out eagle.out.ply

        --verbose

        --voxelDepth 8

        --pointWeight 4.000000

        --voxel eagle.out.iso

        --density

        --color 16.000000

        --performance

Input Points / Samples: 796825 / 117941

# Read input into tree:       0.8 (s),      20.5 (MB) /      20.5 (MB) /      22.0 (MB)

#   Got kernel density:       0.0 (s),      24.3 (MB) /      24.3 (MB) /      24.6 (MB)

#     Got normal field:       0.2 (s),      40.6 (MB) /      40.6 (MB) /      40.9 (MB)

#       Finalized tree:       0.3 (s),      58.9 (MB) /      58.9 (MB) /      61.5 (MB)

#  Set FEM constraints:       0.7 (s),      63.1 (MB) /      63.1 (MB) /      63.1 (MB)

#Set point constraints:       0.2 (s),      60.0 (MB) /      63.1 (MB) /      63.1 (MB)

Leaf Nodes / Active Nodes / Ghost Nodes: 767355 / 876976 / 1

Memory Usage: 60.000 MB

Depth[0/8]:     Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (64.734 MB)     Nodes: 1

Depth[1/8]:     Evaluated / Got / Solved in:  0.000 /  0.000 /  0.001   (64.793 MB)     Nodes: 8

Depth[2/8]:     Evaluated / Got / Solved in:  0.000 /  0.000 /  0.002   (64.809 MB)     Nodes: 64

Depth[3/8]:     Evaluated / Got / Solved in:  0.000 /  0.005 /  0.003   (64.926 MB)     Nodes: 512

Depth[4/8]:     Evaluated / Got / Solved in:  0.000 /  0.025 /  0.006   (66.219 MB)     Nodes: 4096

Depth[5/8]:     Evaluated / Got / Solved in:  0.000 /  0.090 /  0.026   (82.309 MB)     Nodes: 32768

Depth[6/8]:     Evaluated / Got / Solved in:  0.001 /  0.090 /  0.048   (92.527 MB)     Nodes: 62464

Depth[7/8]:     Evaluated / Got / Solved in:  0.003 /  0.239 /  0.176   (124.223 MB)    Nodes: 220312

Depth[8/8]:     Evaluated / Got / Solved in:  0.012 /  0.547 /  0.353   (143.406 MB)    Nodes: 526368

# Linear system solved:       1.7 (s),     143.4 (MB) /     143.4 (MB) /     143.4 (MB)

Got average:       0.1 (s),      56.7 (MB) /     143.4 (MB) /     143.4 (MB)

Iso-Value: 4.948751e-01

Got voxel grid:       1.8 (s),     183.5 (MB) /     183.5 (MB) /     183.5 (MB)

Vertices / Polygons: 138904 / 277796

#        Got triangles:       1.0 (s),      73.8 (MB) /     183.5 (MB) /     183.5 (MB)

#          Total Solve:       7.0 (s),     183.5 (MB)

Time (Wall/User/Kernel): 7.06 / 5.48 / 0.67

Peak Memory (MB): 183

**Comment by knihtyang** [comment]
Run the error are not related to  the several parameters， other Release model（
“Bin\**Win32\Release**\PoissonRecon.exe”,“Bin\**x64\Debug**\PoissonRecon.exe”）with these parameter  (**Bin\x64\Debug\PoissonRecon.exe --in data2\eagle\eagle.points.ply  --pointWeight 4  --color 16 --depth 8 --out data2\eagle\eagle.screend8d.ply --density --voxel eagel.screend10.iso --voxelDepth 8 --performance  --bType 2**
)can run while only in the “Bin\Win32\Release\PoissonRecon.exe” only running **PoissonRecon.exe** report error,
![image](https://cloud.githubusercontent.com/assets/13538712/19276622/93fa0518-9009-11e6-9cfc-c15159090c94.png)

now I chose  “Bin\Win32\Release\PoissonRecon.exe” model runnig these parameter.

**Comment by mkazhdan** [comment]
Unfortunately, I cannot translate the output.

To double-check, it sounds like the error is happening regardless of the parameters you use. Does that mean that you get the error even if you provide no parameters?

Did you try compiling so that it doesn’t use the advanced instruction set?

 

-- Misha
