### ISSUE TITLE
does depth hull mean voxel hull. this is very confused。

### ISSUE THREAD

**Issue by guyuezuntinggithub** [mkazhdan/PoissonRecon#166]

**Comment by mkazhdan** [comment]
I'm not sure which reference to "depth hull" you have in mind.

**Comment by guyuezuntinggithub** [comment]
this paper 《Poisson Surface Reconstruction with Envelope Constraints》。as shown in the follow picture
![image](https://user-images.githubusercontent.com/63081832/93414759-879a1a00-f8d4-11ea-9cc6-9178a37d0f8a.png)

**Comment by guyuezuntinggithub** [comment]
Figure 1: Given a collection of range scans, one can obtain a set of oriented points and a depth hull volume

**Comment by mkazhdan** [comment]
Nope. "Depth hull" does not mean "voxel hull". I don't think. (I'm not actually sure what a "voxel hull" is.)
Given a set of range scans and associated camera positions, you can identify regions of the space where no surface can be:
1. Given a point on the range scan, the line segment between the point and the camera must not contain any surface. (Otherwise the point would not have been seen.)
2. Given the silhouette of a range scan, all rays starting at the camera and passing through some pixel outside the hull cannot intersect the shape. (Otherwise there would be a point on the range-scan and it would not be outside the hull.)
#2 is (I believe) called the "visual hull". The combination of #1 and #2 are called the "depth hull".

This can be represented by the 2D surface defining the boundary of the region where we know no surface can be.

**Comment by guyuezuntinggithub** [comment]
very appreciate for your answer。I get that。
