### ISSUE TITLE
stochastic vert placement?

### ISSUE THREAD

**Issue by abby-normal2** [mkazhdan/PoissonRecon#188]
greetings.  when executing mesh construction on a fixed set of data, the output verts
are 'slightly' stochastic.  meaning ... execute the construction twice, and out of (e.g.)
3000 vertices, most are indistinguishable between the two results, but maybe 20 are 
'slightly' displaced between the two executions.  

we're using version 8. 

is this anticipated?  (apologies if this has been addressed elsewhere)

**Comment by mkazhdan** [comment]
Does a similar problem happen if you add the parameter "--threads 1"?
The only place where I could see some stochasticity coming into play is the multithreading. (E.g. One could get slightly different estimates of the iso-value when using parallel accumulation, due to rounding, which in turn could slightly affect the position of vertices.)

**Comment by abby-normal2** [comment]
thanks professor ... that kinda has the ring of truth about it.  trying it now ...

**Comment by abby-normal2** [comment]
greetings professor.  that was it ... identical final mesh with "-- threads 1".  
very interesting behavior.  thank you so much for your insight.
