### ISSUE TITLE
When the Depth is certain how does pointWeight change

### ISSUE THREAD

**Issue by knihtyang** [mkazhdan/PoissonRecon#19]
When the Depth and others parameters is certain, pointweight  is respectively 1,2,4,8,16,the corresponding CPU time  is 73.53s，73.18s.72.63s， 77,78s and 77.56s. Shouldn't   CPU time  like a logarithmic increase?Can you help me to answer this questions，thanks.

**Comment by mkazhdan** [comment]
I’m not sure I follow. Why should the running time differ depending on the weights?

The underlying linear system looks something like ( A + pointWeight * B ) for two sparse matrices A and B which are independent of the point weights. The resulting system will have the same sparsity structure and since we are using a fixed number of iterations at each level, should take the same amount of time to construct/solve.

 

-- Misha
