### ISSUE TITLE
Poisson reconstruction seemingly ignoring envelope

### ISSUE THREAD

**Issue by lhethert** [mkazhdan/PoissonRecon#208]
I have a dataset for you that should enable you to reproduce the issue. Attached is an envelope and a point cloud (cut down from the full dataset). I run the Poisson reconstruction application with the --envelope argument as well as the --bType 2 and --depth 12 arguments.
 
In this dataset, the input points have a series 3 of holes on the bottom:
![image](https://user-images.githubusercontent.com/4288888/145518622-c62909b3-643e-4dc5-a0fe-bfcd06e1fd16.png)

The envelope I’ve generated also includes the holes:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/4288888/145518653-d918ef80-45a1-4e18-98d9-15cea5791ebc.png">

The resulting reconstruction seems to ignore the holes altogether:
![image](https://user-images.githubusercontent.com/4288888/145518680-d3fa065f-9b02-4940-a5c1-ad94a95b3ee3.png)

DM me for access to sample data and I'll link you.

**Comment by lhethert** [comment]
There is also a large section of points on the left that I would have thought would be excluded, as they also lie outside the envelope:
![image](https://user-images.githubusercontent.com/4288888/145519452-9747ac6d-cca8-4648-9c09-34789009ddee.png)

**Comment by mkazhdan** [comment]
I believe that the issue has to do with what is described in Section 4.2 (Erosion of exterior):
To address this, we erode the exterior designator so that the envelope contains the support of V. The constraint vector field, V is represented as a linear combination of the B-splines, {B_o}, with a 3D vector associated to each B-spline. For an octree node o ∈ O.
That is, in regions where the vector field V is non-vanishing (near the points) the interpolation constraints are ignored.

In the implementation, how far V gets distributed depends on the value of the "--fullDepth" parameter as well as the "--envelopeDepth" parameter. In particular, I found that if I run with --depth 9 --envelopeDepth 8 --fullDepth 7 the three holes start to appear.

However, if you explicitly have samples outside the envelope, then the envelope will necessarily be eroded around those samples to allow for a reconstruction in that area.

**Comment by lhethert** [comment]
I can reproduce your results on the small cut down dataset, but once i try it on my larger dataset, the detail is again lost.

**Comment by mkazhdan** [comment]
My guess is that on the full dataset the corresponding size of the holes are finer than the prescribed depth. E.g. if the bounding cube  of the full dataset is 2^k larger than the bounding box of the cut-out, you'll need to increase the corresponding depth values by k.

**Comment by lhethert** [comment]
Thanks. Sounds like I need a bigger computer!

Any chance you can elaborate on the difference between --depth, --envelopeDepth and --fullDepth and how to intuit the required settings?

**Comment by mkazhdan** [comment]
--depth describes the finest depth at which octree nodes could be generated. Assuming that the model fits in the unit cube (and ignoring sparse sampling) a value of d means the finest resolution nodes will have width 2^{-d}.
--fullDepth describes the depth (at and) below which the octree is a completely refined. (That is, we have a regular voxel grid.)
--envelopeDepth is the depth into which the envelope geometry is rasterized. (It has to be at least as large as --fullDepth.)

**Comment by lhethert** [comment]
Thanks! I will close this now as I think a solution has been provided - just need to find the correct values and compute requirements for our dataset.
