### ISSUE TITLE
(Question) Poisson: Why is the default scale factor 1.1?

### ISSUE THREAD

**Issue by cmosig** [mkazhdan/PoissonRecon#243]
I understand what the scale factor does, but why would the default be 1.1?  
Is it so that the algorithm is able to generate surfaces outside of the actual pointcloud bounding boxes which is in most cases more realistic than stopping right at the pointcloud edge? I am trying to get an intuition.

**Comment by mkazhdan** [comment]
It's likely that a smaller value would also work. But it needs to be larger than 1 so that the surface "can turn around". Picture having samples on the sphere but not having any samples right at the north pole. If you use a value of 1, you would get a sphere clipped to the height of the highest sample point.

**Comment by mkazhdan** [comment]
PS How much room you need to "turn around in" depends on stuff like the surface curvature and the point sampling density. Empirically, 1.1 seems to work as well. But you could also use a larger value and a higher depth. (E.g. using a value of 2.2 with a depth of +1 should generate the same results in the same time/memory.)

So you could also think of the scale value as supporting a continuous resolution.

**Comment by cmosig** [comment]
I see, that makes a lot of sense, thank you!
