### ISSUE TITLE
Stdin/stdout support

### ISSUE THREAD

**Issue by twolfson** [mkazhdan/PoissonRecon#45]
We've been loving this library but recently realized that our code is executing in an environment where disk space is shared across multiple requests. For compliance purposes, we need to either use encrypted files on disk (would definitely require a fork), switch how we're passing information to `PoissonRecon`, or something else

One promising option we can think of is to pass in files via `stdin` and receive the result via `stdout` (leaving `stderr` to report any issues). There's at least 1 rabbit hole down the avenue but aside from that it seems straightforward:

- We currently sniff filenames to determine how to parse the data
    - https://github.com/mkazhdan/PoissonRecon/blob/16375a78928bd67b4cad1a410131f4b5f0afabde/Src/PoissonRecon.cpp#L478-L481
    - Most likely easily resolved if we add another flag for how to parse input (and probably how to output as well)

We'd be more than happy to help out with implementing a solution to this issue =)

**Comment by mkazhdan** [comment]
Hi Todd,

 

One potential problem with using stdin and stderr is that the I/O is not serial.

This happens on both the reading and writing end.

On the reading end, the point-set needs to be read several times.

On the writing end, a temporary file is created which stores partial data. Then this file is read and turned into a .ply file.

 

What kind of datasets are you working with? E.g. are the point-sets small enough to be stored in main memory?

 

-- Misha

**Comment by twolfson** [comment]
We usually have about 80k vertices, totaling at 2-5MB for a `.ply` file. We are going to need to avoid all temporary files to achieve our compliance. Would it be plausible to add support buffering everything in memory if the data set is small enough like ours?

**Comment by mkazhdan** [comment]
Absolutely.

 

On the input side you will need to replace the point-stream with one of your choosing.

The only thing the PoissonRecon assumes is that your point stream is derived from OrientedPointStream (or OrientedPointStreamWithData) in PointStream.[h/inl].

That is, the stream can be queried for the next point (returning false if there are no other points) and the stream can be reset.

One way to do this is to use the MemoryOrientedPointStream class which stores the data in memory. You would just need to read in the points from STDIN and construct an instance of the MemoryOrientedPointStream by passing a pointer to the data.

 

On the output side things are a little trickier, but still manageable.

You will need to replace the declaration of in Line 605 of PoissonRecon.cpp:

              CoredFileMeshData< Vertex > mesh( tempHeader );

to declare “mesh” so that it stores the temporary data in-core:

              CoredVectorMeshData< Vertex > mesh();

Then you will need to modify/replace the calls to PlyWritePolygons (Lines 672, 673, 677, 678) to dump the surface to stdout in whatever format you like. (Note that CoredFileMeshData and CoredVectorMeshData are both derived classes of CoredMeshData, declared in Geometry.h, and have methods iterating over the polygons/vertices of the surface.)

 

-- Misha

**Comment by twolfson** [comment]
Thanks for the detailed explanation! So if I'm understanding correctly, you'd like for us to fork instead of adding this functionality via CLI flags. Is that correct?

**Comment by mkazhdan** [comment]
I think so. (I am not actually that familiar with the git protocol. In the past I have manually looked over the changelog and merged in the modifications. Though this approach is clearly inefficient and error-prone…)

 

-- Misha

**Comment by twolfson** [comment]
Okie doke. I'll close this issue then

For reference: Fork means to take the existing copy of the repository and copy it as your own. In this scenario, we'd be copying (aka forking) and adding our own modifications which would not be added back to original (aka upstream) repository

Thanks for all your help!

**Comment by twolfson** [comment]
If anyone's interesting in a fork supporting this, we wound up hiring a contractor to take care of it. They went the compiler route for using an in-memory file system + CLI flags for `stdin/stdout`:

https://github.com/StandardCyborg/PoissonRecon/tree/836ffe36518921c78063c63bdf3aa262f64df5a0
