### ISSUE TITLE
Memory control of the algorothm

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#59]
Hi. Many days ago I asked a question about how to compute node neighbors. You said that when computing neighbors in a certain depth (level), all node neighbors in lower (parent) depth should be known. I think much memory will be consumed when storing all node 2-ring (125 in total) neighbors, since you may use 2nd order B-splines, where the suppor function range is [-1.5, 1.5]. However I noticed that your program consumes really small memory and computes very fast! I'm really amazed at this memory control and speed. I wonder how could you control the memory so well ?

**Comment by mkazhdan** [comment]
I think I may not have been clear. We have a data-structure that stores the (2-ring) neighbors of a node as well as the (2-ring) neighbors of its ancestors. 

However, we do not store this for each node. (That would be memory-prohibitive.) Instead, we compute it on-the-fly. What makes this efficient are two observations:
1. If we know the (2-ring) neighbors of a node's parent, we can compute the (2-ring) neighbors of the node efficiently. 
2. As we move from one node to a neighbor, the (2-ring) neighbors of most ancestors will remain unchanged, so that updating the data-structure is not very expensive. 

-- Misha

**Comment by antibes0415** [comment]
Your data structure of storing neighbors looks very delicate.  I think it's not very easy to implement that in a short time.
Instead, I'm aware that it only needs 1-ring instead of 2-ring ancestor neighbors for a node to compute its 2-ring neighbors. So I stored 1-ring neighbors of all nodes, except for max depth nodes. When I need 2-ring neighbors of a node, I will compute them by referring to lookup tables and the 1-ring neighbors of its ancestor.
